alter table VAULT_ERROR_SUMMARY add constraint FK_VAULT_ERROR_SUMMARY_ON_ERR_UPL foreign key (ERR_UPL_ID) references VAULT_UPLOAD_SUMMARY(ID);
create index IDX_VAULT_ERROR_SUMMARY_ON_ERR_UPL on VAULT_ERROR_SUMMARY (ERR_UPL_ID);
