create table VAULT_INT_DETAILS (
    ID bigserial,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    --
    INT_UPL_ID bigint,
    INT_ASSET_ID varchar(255) not null,
    INT_NAME varchar(500) not null,
    INT_DESC text,
    INT_CRUD_ID bigint,
    INT_PAYLOAD text,
    INT_PAYLOAD_SECUR_CLASS_ID bigint,
    INT_BRAND_OR_BU_ID bigint,
    INT_REGION_ID bigint,
    INT_COUNTRY_ID bigint,
    INT_PLATFORM_ID bigint,
    INT_PLATFORM_VERSION_ID bigint,
    INT_SRC_PROTOCOL_ID bigint,
    INT_SRC_PAYLOAD_TYPE_ID bigint,
    INT_DEST_APP_ID bigint,
    INT_DEST_PROTOCOL_ID bigint,
    INT_DEST_PAYLOAD_TYPE_ID bigint,
    INT_DESIGN_PATTERN_ID bigint,
    INT_IMPL_PATTERN varchar(255),
    INT_COMPLEXITY_ID bigint,
    INT_THROUGHPUT_IN_SECONDS varchar(255),
    INT_MSG_SIZE_IN_KB varchar(255),
    INT_OWNER varchar(255),
    INT_BA varchar(255),
    INT_PROJECT varchar(255),
    INT_PRIORITY_ID bigint,
    INT_WORKSTREAM_ID bigint,
    INT_PROCESSING_TYPE varchar(255),
    INT_INITIATING_SYS_ID bigint,
    INT_SPL_OPS_ID bigint,
    INT_DEPENDENCY varchar(255),
    INT_BUSINESS_OWNER varchar(255),
    INT_REMARKS varchar(255),
    INT_F_SPEC_LOC varchar(255),
    INT_LOB_ID bigint,
    INT_STATUS_ID bigint,
    INT_INTERNAL_STATUS varchar(50) not null,
    --
    primary key (ID)
);