alter table VAULT_INT_API_DETAILS add constraint FK_VAULT_INT_API_DETAILS_ON_INT_DETAILS foreign key (INT_DETAILS_ID) references VAULT_INT_DETAILS(ID);
alter table VAULT_INT_API_DETAILS add constraint FK_VAULT_INT_API_DETAILS_ON_API_DETAILS foreign key (API_DETAILS_ID) references VAULT_API_DETAILS(ID);
create index IDX_VAULT_INT_API_DETAILS_ON_INT_DETAILS on VAULT_INT_API_DETAILS (INT_DETAILS_ID);
create index IDX_VAULT_INT_API_DETAILS_ON_API_DETAILS on VAULT_INT_API_DETAILS (API_DETAILS_ID);
