alter table VAULT_INT_DETAILS add constraint FK_VAULT_INT_DETAILS_ON_INT_UPL foreign key (INT_UPL_ID) references VAULT_UPLOAD_SUMMARY(ID);
create index IDX_VAULT_INT_DETAILS_ON_INT_UPL on VAULT_INT_DETAILS (INT_UPL_ID);
