create table VAULT_API_DETAILS (
    ID bigserial,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    --
    API_UPL_ID bigint,
    INT_ASSET_ID bigint,
    API_NAME varchar(500) not null,
    API_DESCRIPTION text,
    API_CLASSIFICATION_ID bigint,
    API_SUPPORTED_OPS_ID bigint,
    API_ENTITY_NAME varchar(255),
    API_PAYLOAD_SECUR_CLASS_ID bigint,
    API_BRAND_OR_BU_ID bigint,
    API_REGION_ID bigint,
    API_COUNTRY_ID bigint,
    API_PROJECT_ID bigint,
    API_PRIORITY_ID bigint,
    API_STATUS_ID bigint,
    API_PROCESSING_TYPE varchar(255),
    API_BUSINESS_OWNER varchar(255),
    API_WORKSTREAM_ID bigint,
    API_RELEASE varchar(255),
    API_PLATFORM_ID bigint,
    API_PLATFORM_VERSION_ID bigint,
    API_SRC_PROTOCOL_ID bigint,
    API_SRC_PAYLOAD_TYPE_ID bigint,
    API_DEST_APP_ID bigint,
    API_DEST_PROTOCOL_ID bigint,
    API_DEST_PAYLOAD_TYPE_ID bigint,
    API_DESIGN_PATTERN_ID bigint,
    API_COMPLEXITY_ID bigint,
    API_THROUPUT_IN_SEC varchar(255),
    API_INT_MESSAGE_SIZE_IN_KB varchar(255),
    API_DEPENDENCY varchar(255),
    API_INT_OWNER varchar(255),
    API_REMARKS text,
    API_LOB_ID bigint,
    API_INTERNAL_STATUS varchar(50) not null,
    --
    primary key (ID)
);