create table VAULT_INT_DETAILS (
    ID bigserial,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    --
    INT_NAME varchar(500),
    INT_DESC varchar(5000),
    INT_PAYLOAD varchar(5000),
    INT_IMPL_PATTERN varchar(255),
    INT_THROUGHPUT_IN_SEC double precision,
    INT_MSG_SIZE integer,
    INT_OWNER varchar(255) not null,
    INT_BA varchar(255),
    INT_PROCESSING_TYPE varchar(255),
    INT_DEPENDENCY varchar(255),
    INT_BUSINESS_OWNER varchar(255),
    INT_REMARK text,
    INT_F_SPEC_LOC varchar(255),
    INT_SRC_CODE_REPO varchar(255),
    INT_REPO_LOC varchar(255),
    INT_LINK varchar(255),
    INT_TECH_SPEC_LOC varchar(255),
    INT_INTERNAL_STATUS varchar(255),
    INT_ASSET integer not null,
    INT_REGION_ID bigint,
    INT_UPL_ID bigint,
    INT_PRIORITY_ID bigint,
    INT_CRUD_ID bigint,
    INT_PAYLOAD_SECUR_CLASS_ID bigint,
    INT_BRAND_OR_BU_ID bigint,
    INT_COUNTRY_ID bigint,
    INT_PLATFORM_ID bigint,
    INT_PLATFORM_VERSION_ID bigint,
    INT_SRC_PROTOCOL_ID bigint,
    INT_SRC_PAYLOAD_TYPE_ID bigint,
    INT_DEST_APP_ID bigint not null,
    INT_DEST_PROTOCOL_ID bigint,
    INT_DEST_PAYLOAD_TYPE_ID bigint,
    INT_DESIGN_PATTERN_ID bigint,
    INT_COMPLEXITY_ID bigint,
    INT_PROJECT_ID bigint,
    INT_WORKSTREAM_ID bigint,
    INT_INITIATING_SYS_ID bigint,
    INT_SPL_OPS_ID bigint,
    INT_LOB_ID bigint,
    INT_STATUS_ID bigint,
    --
    primary key (ID)
);