alter table VAULT_UPLOAD_SUMMARY add constraint FK_VAULT_UPLOAD_SUMMARY_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_VAULT_UPLOAD_SUMMARY_ON_USER on VAULT_UPLOAD_SUMMARY (USER_ID);
