alter table VAULT_ERROR_TABLE add constraint FK_VAULT_ERROR_TABLE_ON_ERR_UPL foreign key (ERR_UPL_ID) references VAULT_UPLOAD_SUMMARY(ID);
create index IDX_VAULT_ERROR_TABLE_ON_ERR_UPL on VAULT_ERROR_TABLE (ERR_UPL_ID);
