create table VAULT_API_DETAILS (
    ID bigserial,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    --
    API_UPL_ID bigint,
    API_BUSINESS_OWNER varchar(255),
    API_RELEASE varchar(255),
    API_THROUGHPUT_IN_SEC double precision,
    API_INT_MSG_SIZE varchar(255),
    API_DEPENDENCY varchar(255),
    API_INT_OWNER varchar(255),
    API_REMARK varchar(255),
    API_CLASSIFICATION_ID bigint,
    API_SUPPORTED_OPS_ID bigint,
    API_NAME varchar(500) not null,
    API_DESC varchar(1000),
    API_INTERNAL_STATUS varchar(50),
    API_ENTITY_NAME varchar(255),
    API_PROCESSING_TYPE varchar(255),
    API_SPECIAL_OPS varchar(255),
    API_IMPL_PATTER varchar(255),
    API_PAYLOAD_SECUR_CLASS_ID bigint,
    API_BRAND_OR_BU_ID bigint,
    API_REGION_ID bigint,
    API_COUNTRY_ID bigint,
    API_PROJECT_ID bigint,
    API_STATUS_ID bigint,
    API_WORKSTREAM_ID bigint,
    API_PLATFORM_ID bigint,
    API_PLATFORM_VERSION_ID bigint,
    API_SRC_PROTOCOL_ID bigint,
    API_SRC_PAYLOAD_TYPE_ID bigint,
    API_DEST_APP_ID bigint,
    API_DEST_PROOCOL_ID bigint,
    API_DEST_PAYLOAD_TYPE_ID bigint,
    API_DESIGN_PATTERN_ID bigint,
    API_COMPLEXITY_ID bigint,
    API_LOB_ID bigint,
    API_PRIORITY_ID bigint,
    --
    primary key (ID)
);